name: Deploy Frontend Only

on:
  # 1. Cho phÃ©p báº¥m nÃºt cháº¡y thá»§ cÃ´ng
  workflow_dispatch:

  # 2. Tá»± cháº¡y khi push code
  push:
    branches:
      - main
      - master
    paths:
      - "Frontend/**" # Chá»‰ cháº¡y khi sá»­a file trong Frontend

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    name: ğŸ‰ Deploy HTML Frontend
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ“‚ Sync Frontend to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.IF_HOST }}
          username: ${{ secrets.IF_USER }}
          password: ${{ secrets.IF_PASS }}

          # Láº¥y code tá»« thÆ° má»¥c Frontend
          local-dir: ./Frontend/

          # Äáº©y vÃ o htdocs (chung nhÃ  vá»›i Backend)
          server-dir: htdocs/

          # KhÃ´ng xÃ³a file cá»§a Backend
          dangerous-clean-slate: false
